free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),

    path('broadcasting_list/', views.BroadcastingListView.as_view(), name='broadcasting_list'),
    path('musicvideo_list/', views.MusicvideoListView.as_view(), name='musicvideo_list'),
    path('show_list/', views.ShowListView.as_view(), name='show_list'),
    path('etc_list/', views.EtcListView.as_view(), name='etc_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),

]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'notice'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.NoticeListView.as_view(), name='notice_list'),
    path('write/', views.notice_write_view, name='notice_write'),
    path('<int:pk>/', views.notice_detail_view, name='notice_detail'),
    path('<int:pk>/edit/', views.notice_edit_view, name='notice_edit'),
    path('<int:pk>/delete/', views.notice_delete_view, name='notice_delete'),
    path('download/<int:pk>', views.notice_download_view, name="notice_download"),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),

]

notice/models.py
import os
from django.conf import settings
from django.db import models
from uuid import uuid4
from django.utils import timezone
from datetime import datetime

# import hashlib

# def get_file_path(instance, filename):
#     base = 'upload_file/%Y/%m/%d'
#     parts = os.path.splitext(filename)
#     ctx = hashlib.sha256()
#     return base + ctx.hexdigest() + parts[1]

def get_file_path(instance, filename):
    # ymd_path = timezone.now().strftime('%Y/%m/%d')
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    # extension = os.path.splitext(filename)[-1].lower()
    # return '/'.join(['upload_file/', ymd_path, uuid_name + extension,])
    return '/'.join(['upload_file/', ymd_path, uuid_name])

# def get_image_path(get_file_path):
#   return '/'.join(['upload_file/', ymd_path, uuid_name])


class Notice(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    upload_images = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일')
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    top_fixed = models.BooleanField(verbose_name='상단고정', default=False)
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

    def __str__(self):
        return self.title

    # def get_filename(self):
    #     return os.path.basename(self.upload_files.name)

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Notice, self).delete(*args, **kargs)

    class Meta:
        db_table = '공지사항'
        verbose_name = '공지사항'
        verbose_name_plural = '공지사항'

notice/forms.py
from django import forms
from .models import Notice

# from django.forms import FileInput, ClearableFileInput
# from django.utils.safestring import mark_safe

# class CustomFileWidget(forms.FileInput):
#     def __init__(self, attrs={}):
#         super(CustomFileWidget, self).__init__(attrs)

#     def render(self, name, value, attrs=None, renderer=None):
#         output = []
#         if value and hasattr(value, "url"):
#             output.append('%s <a target="_blank" href="%s">%s</a> <br />%s' %('첨부파일 :', value.url, value, '변경:'))
#         output.append(super(CustomFileWidget, self).render(name, value, attrs))
#         return mark_safe(u''.join(output))

class NoticeWriteForm(forms.ModelForm):
    # files = forms.FileField(widget=forms.ClearableFileInput(attrs={
    #     'multiple': True
    #     }))
    def __init__(self, *args, **kwargs):
        super(NoticeWriteForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'id': 'form_title',
            'autofocus': True,
        })

    class Meta:
        model = Notice
        fields = ['title', 'content', 'upload_files', 'top_fixed']
        # widgets = {
        #     'upload_files': CustomFileWidget
        # }

notice/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DetailView, FormView, CreateView
from .models import Notice
from users.decorators import login_message_required, admin_required
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from .forms import NoticeWriteForm
from users.models import User
import mimetypes
from mimetypes import guess_type
import os
import re
from django.http import HttpResponse, HttpResponseRedirect, Http404
from urllib.parse import quote
import urllib
from django.conf import settings

# 공지사항 게시판 권한
# level 2,3 = READ
# level 1 관리자 = CREATE, READ + 본인 글 UPDATE, DELETE
# level 0 개발자 = CREATE, READ, UPDATE, DELETE


# 공지사항 리스트 뷰
class NoticeListView(ListView):
    model = Notice
    paginate_by = 15
    template_name = 'notice/notice_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'notice_list'        #DEFAULT : <app_label>_list

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_list = Notice.objects.order_by('-id') 
        
        if search_keyword :
            if len(search_keyword) > 1 :
                if search_type == 'all':
                    search_notice_list = notice_list.filter(Q (title__icontains=search_keyword) | Q (content__icontains=search_keyword) | Q (writer__user_id__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_notice_list = notice_list.filter(Q (title__icontains=search_keyword) | Q (content__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = notice_list.filter(title__icontains=search_keyword)    
                elif search_type == 'content':
                    search_notice_list = notice_list.filter(content__icontains=search_keyword)    
                elif search_type == 'writer':
                    search_notice_list = notice_list.filter(writer__user_id__icontains=search_keyword)

                # if not search_notice_list :
                #     messages.error(self.request, '일치하는 검색 결과가 없습니다.')
                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return notice_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_fixed = Notice.objects.filter(top_fixed=True).order_by('-registered_date')

        if len(search_keyword) > 1 :
            context['q'] = search_keyword
        context['type'] = search_type
        context['notice_fixed'] = notice_fixed

        return context


# 공지사항 게시글 보기
@login_message_required
def notice_detail_view(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    # notice = Notice.objects.filter(id=pk)
    session_cookie = request.session['user_id']
    cookie_name = F'notice_hits:{session_cookie}'

    if request.user == notice.writer:
        notice_auth = True
    else:
        notice_auth = False

    context = {
        'notice': notice,
        'notice_auth': notice_auth,
    }
    response = render(request, 'notice/notice_detail.html', context)

    # 조회수 GET증가 방지 쿠키처리
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(pk) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{pk}', expires=None)
            # notice.update(hits=F('hits') + 1)
            notice.hits += 1
            notice.save()
            return response
    else:
        response.set_cookie(cookie_name, pk, expires=None)
        # notice.update(hits=F('hits') + 1)
        notice.hits += 1
        notice.save()
        return response
    return render(request, 'notice/notice_detail.html', context)


# 공지사항 글쓰기
@login_message_required
@admin_required
def notice_write_view(request):
    if request.method == "POST":
        form = NoticeWriteForm(request.POST, request.FILES)
        user = request.session['user_id']
        user_id = User.objects.get(user_id = user)
        # upload_files = request.FILES.getlist('files')

        if form.is_valid():
            notice = form.save(commit = False)
            notice.writer = user_id
            # 첨부파일명 save
            if request.FILES:
                if 'upload_files' in request.FILES.keys():
                    notice.filename = request.FILES['upload_files'].name
                # extension = notice.filename.split(".")[1].lower()
                # notice.extension = '.' + extension
            notice.save()
            return redirect('notice:notice_list')
    else:
        form = NoticeWriteForm()
    return render(request, "notice/notice_write.html", {'form': form})


# 공지사항 게시글 수정
@login_message_required
def notice_edit_view(request, pk):
    notice = Notice.objects.get(id=pk)

    if request.method == "POST":
        if(notice.writer == request.user or request.user.level == '0'):

            file_change_check = request.POST.get('fileChange', False)
            file_check = request.POST.get('upload_files-clear', False)
            
            if file_check or file_change_check:
                os.remove(os.path.join(settings.MEDIA_ROOT, notice.upload_files.path))

            form = NoticeWriteForm(request.POST, request.FILES, instance=notice)
            if form.is_valid():
                # test-------------------------------#
                notice = form.save(commit = False)
                if request.FILES:
                    if 'upload_files' in request.FILES.keys():
                        notice.filename = request.FILES['upload_files'].name
                notice.save()
                #------------------------------------#
                # form.save()
                messages.success(request, "수정되었습니다.")
                return redirect('/notice/'+str(pk))
    else:
        notice = Notice.objects.get(id=pk)
        if notice.writer == request.user or request.user.level == '0':
            form = NoticeWriteForm(instance=notice)
            # test---------------------------------------------------------#
            context = {
                'form': form,
                'edit': '수정하기',
            }
            if notice.filename and notice.upload_files:
                context['filename'] = notice.filename
                context['file_url'] = notice.upload_files.url
            #--------------------------------------------------------------#
            # return render(request, "notice/notice_write.html", {'form': form, 'edit': '수정하기'})
            return render(request, "notice/notice_write.html", context)
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
            return redirect('/notice/'+str(pk))


# 공지사항 게시글 삭제
@login_message_required
def notice_delete_view(request, pk):
    notice = Notice.objects.get(id=pk)
    if notice.writer == request.user or request.user.level == '0':
        notice.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('/notice/')
    else:
        messages.error(request, "본인 게시글이 아닙니다.")
        return redirect('/notice/'+str(pk))


# 공지사항 게시글 첨부파일 다운로드 한글명 인코딩
@login_message_required
def notice_download_view(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    url = notice.upload_files.url[1:]
    file_url = urllib.parse.unquote(url)
    
    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            # quote_file_url = urllib.parse.quote(file_url.encode('utf-8'))
            quote_file_url = urllib.parse.quote(notice.filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            # response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url[29:]
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

templates/notice/notice_detail.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<br><br><br>
<div class="container">
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header">
                    <strong style="font-size: 18px;">{{ notice.title }}</strong>&nbsp;&nbsp;<span style="font-size: 18px; color: gray;">[공지사항]</span>
                    <span style="float:right;">{{ notice.registered_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body" style="min-height: 400px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ notice.writer }}</span>
                        <span style="float:right;">조회수 : {{ notice.hits }}</span>
                    </div>
                    <hr>
                    {% if notice.upload_files %}
                    <div class="col-12 text-right">
                        <span style="color: gray;">첨부파일 :&nbsp;</span>
                        <a id="id_uploaded_file" href="{% url 'notice:notice_download' notice.id %}" >{{ notice.filename|truncatechars:25 }}</a>
                    </div>
                    {% endif %}
                    <!--내용-->
                    <div>
                        {{ notice.content | safe }}
                    </div>
                </div>
            </div>
            <br>
            <div class="text-right" style="margin-top:-15px;">
                {% if notice_auth or request.user.level == '0' %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/{{ notice.id }}/edit/'">수정</button>
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal">삭제</button>
                <!-- <button class="btn btn-md btn-dark" onclick="location.href='/notice/{{ notice.id }}/delete/'">삭제</button> -->
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/'">목록으로</button>
                {% else %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/'">목록으로</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">삭제경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>게시글을 삭제하시겠습니까?</p>
                </div>
                <div class="modal-footer">
                    <button onclick="delete_modal()" type="button" class="btn btn-dark">삭제하기</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">취소하기</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('img').css('width', '100%');
    });

    function delete_modal() {
        location.replace('/notice/{{ notice.id }}/delete/');
    }
</script>

{% endblock %}

templates/notice/notice_write.html
{% extends "users/main_base.html" %}
{% load humanize %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block summernote %}
<!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script> -->

<link rel="stylesheet" href="{% static 'css/summernote/summernote.css' %}" type="text/css">
<script src="{% static 'js/summernote/summernote.js' %}"></script>
<!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-lite.min.css" rel="stylesheet"> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-lite.min.js"></script> -->

<script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>
<script>
    $(document).ready(function () {
        $('#id_content').summernote({
            placeholder: '내용을 입력해주세요.',
            height: 500,
            minHeight: 500,
            maxHeight: 500,
            lang: 'ko-KR',
           
            toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'help']]
            ]
        });
        $('p').css('margin-bottom','0')
        $('.note-resizebar').css('display','none');
    });
</script>
<!-- CheckBoxCSS -->
<link rel="stylesheet" href="{% static 'css/users/checkbox.css' %}" type="text/css"> 
{% endblock %}

{% block contents %}
{% load static %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">공지사항</h4>
        </div>
    </div>

    <div class="row-mt-5">
        <!--본문-->
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header" style="padding: 0rem 0.8rem">
                    <div class="md-form form-group" style="margin-top: 8.5px;">
                        <div style="padding: 0 5.5px;">
                            <!-- <label for="form_title" class="control-label">{{ form.title.label }}</label> -->
                            {{ form.title }}
                        </div>
                    </div>
                </div>
                <!-- <div class="card-body">
                    <div class="form-group">
                        <div class=" col-sm-12">
                            {{ form.content }}
                        </div>
                    </div>
                </div> -->
                <div>
                    <!--내용-->
                    {{ form.content }}
                </div>
            </div>
            
            <div class="card-footer" style="padding-left: 0px; margin-top:18px;">
                <div class="form-group">
                    <div class="col-sm-12">
                        {{ form.upload_files }}
                        <small id="help" class="form-text text-muted" style="margin-bottom: -15px;">
                            &nbsp;&nbsp;[파일 업로드]&nbsp;&nbsp;<i class="fas fa-upload"></i>&nbsp;10MB 이하의 파일만 첨부 가능합니다. 여러 파일은 압축해서 업로드해주세요.
                        </small>
                    </div>
                </div>
            </div>
            <div class="text-right" style="margin-top: 10px;">
                <label>
                    {{ form.top_fixed }}
                    <span style="padding-bottom: 35px; color:black; font-weight: bold;">상단에 표시하기</span>
                </label>
                {% if edit %}
                <button type="submit" id="write" class="btn btn-sm">{{ edit }}</button>
                {% else %}
                <button type="submit" id="write" class="btn btn-sm">작성하기</button>
                {% endif %}
                <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });

    // $('#write').click(function () {
    //     if ( $('p')[2].innerText == false ) {
    //         alert('내용을 입력해주세요.');
    //     } else {
    //         checkUnload = false;
    //         $('#id_form').submit();
    //     }
    // });
</script>

{% if filename %}
<script type = "text/javascript">
    $('[href="{{ file_url }}"]').html("{{ filename }}");
    $('#upload_files-clear_id').css({opacity:'100', position:'relative', 'pointer-events':'auto'})

    $("#id_upload_files").change(function() {
        if ($('#id_upload_files').get(0).files.length == 1) {
            $(".col-sm-12").contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'
            $('#upload_files-clear_id').attr("checked", false)
            $('#upload_files-clear_id').prev().hide()
            $('#upload_files-clear_id').next().hide()
            $('#upload_files-clear_id').hide()
        }
    });

    // var result = null;
    // $('<input type="file" />')
    //     .on('change', function () {
    //         result = this.files[0];
    //         alert('selected!');
    //     })
    //     .click();

    // setTimeout(function () {
    //     $(document).one('mousemove', function () {
    //         if (!result) {
    //             alert('cancelled');
    //         }
    //     });
    // }, 1000);

    $('#upload_files-clear_id').on('click', function(){
        if($(this).prop('checked')){
            $('#id_upload_files').hide()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'
        } else{
            $('#id_upload_files').show()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '
        }
    });

    $('#write').click( function() {
        if($('#id_upload_files').get(0).files.length == 1){
            $('#fileChangeCheck').attr("checked",true)
        }
    });
</script>
{% endif %}

{% endblock %}