free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),

    path('broadcasting_list/', views.BroadcastingListView.as_view(), name='broadcasting_list'),
    path('musicvideo_list/', views.MusicvideoListView.as_view(), name='musicvideo_list'),
    path('show_list/', views.ShowListView.as_view(), name='show_list'),
    path('etc_list/', views.EtcListView.as_view(), name='etc_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),

]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('', views.index),
    # path('login/', views.login_view, name='login'),
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
    # path('recovery/reset/', views.AuthPwResetView.as_view(), name='recovery_pw_reset'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/post', views.profile_post_view, name='profile_post'),
    path('profile/comment', views.profile_comment_view, name='profile_comment'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    path('profile/password/', views.password_edit_view, name='password_edit'),
]

free/models.py
import os
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from users.choice import CATEGORY_CHOICES,CATEGORY2_CHOICES
from uuid import uuid4
from notice.models import get_file_path


class Free(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=18, verbose_name='분류', default='자유')
    category2 = models.CharField(choices=CATEGORY2_CHOICES, max_length=18, verbose_name='카테고리', default='기타')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    comments = models.PositiveIntegerField(verbose_name='댓글수', null=True)
    files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일') # summernote MultiValueDict : files
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')



    def __str__(self):
        return self.title

    # def filename(self):
    #     return os.path.basename(self.upload_files.name)

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Free, self).delete(*args, **kargs)



    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.registered_date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.registered_date.date()
            return str(time.days) + '일 전'
        else:
            return False

    class Meta:
        db_table = '자유게시판'
        verbose_name = '자유게시판'
        verbose_name_plural = '자유게시판'


class Comment(models.Model):
    post = models.ForeignKey(Free, on_delete=models.CASCADE, verbose_name='게시글')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='댓글작성자')
    # writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE, verbose_name='댓글작성자')
    # writer = models.CharField(max_length=17, null=True, verbose_name='댓글작성자')
    content = models.TextField(verbose_name='댓글내용')
    created = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    deleted = models.BooleanField(default=False, verbose_name='삭제여부')
    reply = models.IntegerField(verbose_name='답글위치', default=0)
    
    def __str__(self):
        return self.content

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created.date()
            return str(time.days) + '일 전'
        else:
            return False 

    class Meta:
        db_table = '자유게시판 댓글'
        verbose_name = '자유게시판 댓글'
        verbose_name_plural = '자유게시판 댓글'

notice/models.py
import os
from django.conf import settings
from django.db import models
from uuid import uuid4
from django.utils import timezone
from datetime import datetime

# import hashlib

# def get_file_path(instance, filename):
#     base = 'upload_file/%Y/%m/%d'
#     parts = os.path.splitext(filename)
#     ctx = hashlib.sha256()
#     return base + ctx.hexdigest() + parts[1]

def get_file_path(instance, filename):
    # ymd_path = timezone.now().strftime('%Y/%m/%d')
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    # extension = os.path.splitext(filename)[-1].lower()
    # return '/'.join(['upload_file/', ymd_path, uuid_name + extension,])
    return '/'.join(['upload_file/', ymd_path, uuid_name])

# def get_image_path(get_file_path):
#   return '/'.join(['upload_file/', ymd_path, uuid_name])


class Notice(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    upload_images = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일')
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    top_fixed = models.BooleanField(verbose_name='상단고정', default=False)
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

    def __str__(self):
        return self.title

    # def get_filename(self):
    #     return os.path.basename(self.upload_files.name)

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Notice, self).delete(*args, **kargs)

    class Meta:
        db_table = '공지사항'
        verbose_name = '공지사항'
        verbose_name_plural = '공지사항'

users/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, SetPasswordForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model



def hp_validator(value):
	if len(str(value)) != 10:
		raise forms.ValidationError('정확한 핸드폰 번호를 입력해주세요.')


# 로그인 폼
class LoginForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput(
        attrs={'class': 'form-control',}), 
        error_messages={
            'required': '아이디을 입력해주세요.'
        },
        max_length=32,
        label='아이디'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
        error_messages={
            'required': '비밀번호를 입력해주세요.'
        },
        label='비밀번호'
    )

    def clean(self):
        cleaned_data = super().clean()
        user_id = cleaned_data.get('user_id')
        password = cleaned_data.get('password')

        if user_id and password:
            try:
               user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                self.add_error('user_id', '아이디가 존재하지 않습니다.')
                return
            
            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')




# 컴공회원정보 수정 폼
class CustomCsUserChangeForm(UserChangeForm):
    password = None        
    hp = forms.IntegerField(label='연락처', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength':'11', 'oninput':"maxLengthCheck(this)",}), 
    )        
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',}), 
    )        


    class Meta:
        model = get_user_model()
        fields = ['hp', 'name']


# 회원탈퇴 비밀번호확인 폼
class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')


# 아이디찾기 폼
class RecoveryIdForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput,
    )
    email = forms.EmailField(
        widget=forms.EmailInput,
    )

    class Meta:
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super(RecoveryIdForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            # 'placeholder': '이름을 입력해주세요',
            'class': 'form-control',
            'id': 'form_name',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            # 'placeholder': '이메일을 입력해주세요',
            'class': 'form-control',
            'id': 'form_email' 
        })


# 비밀번호찾기 폼
class RecoveryPwForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput,
    )
    name = forms.CharField(
        widget=forms.TextInput,
    )
    email = forms.EmailField(
        widget=forms.EmailInput,
    )
    class Meta:
        fields = ['user_id', 'name', 'email']

    def __init__(self, *args, **kwargs):
        super(RecoveryPwForm, self).__init__(*args, **kwargs)
        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            # 'placeholder': '아이디을 입력해주세요',
            'class': 'form-control',
            'id': 'pw_form_id',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            # 'placeholder': '이름을 입력해주세요',
            'class': 'form-control',
            'id': 'pw_form_name',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            # 'placeholder': '이메일을 입력해주세요',
            'class': 'form-control',
            'id': 'pw_form_email',
        })


# 비밀번호찾기 새 비밀번호 입력 폼
class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomSetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '새 비밀번호',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '새 비밀번호 확인',
        })


# 비밀번호 변경 폼
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
            'style': 'margin-top:-15px;'
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })


# 회원가입 폼
class CsRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CsRegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            # 'class': 'form-control col-sm-10',
            'class': 'form-control',
            # 'placeholder': '아이디를 입력해주세요.',
            'autofocus': False
        })
        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 입력해주세요.',
        })
        self.fields['password2'].label = '비밀번호 확인'
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 다시 입력해주세요.',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '회원가입 후 입력하신 메일로 본인인증 메일이 전송됩니다.',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "아이디, 비밀번호 찾기에 이용됩니다.",
        })
        self.fields['hp'].label = '핸드폰번호'
        self.fields['hp'].validators = [hp_validator]
        self.fields['hp'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "'-'를 제외한 숫자로 입력해주세요",
        })


    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'email', 'name', 'hp']

    def save(self, commit=True):
        user = super(CsRegisterForm, self).save(commit=False)
        user.level = '2'
        user.is_active = False
        user.save()

        return user

templates/users/login.html
{% extends "users/user_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=480, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row justify-content-md-center">
        <div style="position: absolute; top: 40%; height: 476.06px; margin-top: -238.03px;">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <div class="text-center">
                        <h1>FOCUS</h1>
                        <h3>직캠 제작 사이트</h3>
                    </div>

                    <form method="POST" action="." novalidate>
                        {% csrf_token %}

                        <div class="mb-4 md-form">
                            <label name="label_user_id" for="{{ form.user_id.id_for_label }}"><i class="fas fa-user"></i>&nbsp;&nbsp;{{ form.user_id.label }}</label>
                            {{ form.user_id }}
                            <script type="text/javascript">
                                if (document.getElementsByName('user_id')[0].value != '') {
                                    document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
                                }
                            </script>
                            {% if form.user_id.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('user_id')[0].setAttribute('class',
                                    'form-control is-invalid')
                            </script>
                            {% for error in form.user_id.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="mb-4 md-form">
                            <label for="{{ form.password.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;&nbsp;{{ form.password.label }}</label>
                            {{ form.password }}

                            {% if form.password.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                            </script>
                            {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <!-- {{ login_form }} -->
                        <label>
                            <input type="checkbox" name="remember_session"/>
                            <span style="padding-bottom: 35px;">로그인 상태 유지</span>
                        </label>
                        <br>
                        <!-- <input type="checkbox" name="remember_session" > 로그인 상태 유지<br><br> -->

                        <button type="submit" style="opacity: 90%; font-size: 16px; margin-top: -5px;" class="btn btn-dark btn-lg btn-block">로그인</button>
                    </form>
                    <div style="text-align: center;">
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:recovery_id' %}">아이디</a>&nbsp;&middot;
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:recovery_pw' %}">비밀번호찾기</a>&nbsp;&middot;
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:agreement' %}">회원가입</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/main.html
{% extends "users/main_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/index/owl.carousel.min.css' %}">
{% endblock %}

{% block contents %}
<div style="margin: 55px -10px -40px 4px;">
    <br><br>
    <p>dksduds</p>
 
</div>

<script src="{% static 'js/index/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/index/aos.js' %}"></script>
<script src="{% static 'js/index/jquery.sticky.js' %}"></script>
<script src="{% static 'js/index/customCarousel.js' %}"></script>
{% endblock %}

templates/users/profile.html
{% extends "users/main_base.html" %}

{% block mobileView %}
<meta name="viewport" content="width=550, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                    </div>
                    <div class="card-body">
                        <table style="color:black; margin-left:10px;">
                            <tr>
                                <td class="profile_title">아이디</td>
                                {% if user.level == '0'%}
                                <td class="profile_content">{{ user.user_id }}&nbsp;&nbsp;(개발자)</td>
                                {% elif user.level == '1' %}
                                <td class="profile_content">{{ user.user_id }}&nbsp;&nbsp;(관리자)</td>
                                {% else %}
                                <td class="profile_content">{{ user.user_id }}</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td class="profile_title">이메일</td>
                                <td class="profile_content">{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이름</td>
                                <td class="profile_content">{{ user.name }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">연락처</td>
                                <td class="profile_content">0{{ user.hp }}</td>
                            </tr>
                            
                        </table>
    
                        <hr>
                        <div style="text-align: center;">
                        <!-- <div style="margin-left: 10px;"> -->
                            <a href="{% url 'users:profile_update' %}" style="color:#0455BF; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;
                            <a href="{% url 'users:password_edit' %}" style="color:#0455BF; font-size:15px;"><i class="fas fa-user-lock"></i>&nbsp;비밀번호변경</a>&nbsp;&middot;&nbsp;
                            <a href="{% url 'users:profile_delete' %}" style="color:#0455BF; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;회원탈퇴</a> <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/profile_comment.html
{% extends "users/main_base.html" %}
{% load humanize %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/timetable/timetable.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<br><br>
<div class="container">
    <h5><strong><i class="fas fa-comments"></i>&nbsp;작성한 댓글보기</strong></h5>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="free_comment" role="tabpanel" aria-labelledby="free-comment-tab">
            <table class="table table-sm table-hover">
                <thead style="border-top: 1px solid #dee2e6;">
                    <tr class="text-center">
                        <th class="all_view_title"></th>
                        <th class="text-left all_view_title">게시글 제목</th>
                        <th class="text-left all_view_title">댓글내용</th>
                        <th class="all_view_title">작성일</th>
                    </tr>
                </thead>
                <tbody>
                    {% if comment_list %}
                        {% for comment in comment_list %}
                        <tr class="text-center" style="font-weight: bold; cursor:pointer;" onclick="location.href='/free/{{ comment.post.id }}/'">
                            <td class="all_view"></td>
                            <td class="text-left all_view">{{ comment.post|truncatechars:8 }}</td>
                            <td class="text-left all_view" style="width:50%">
                            {{ comment.content|truncatechars:30 }}
                            </td>
                            {% if comment.created_string == False %}
                            <td class="all_view">{{ comment.created|date:'m월 d일' }}</td>
                            {% else %}
                            <td class="all_view">{{ comment.created_string }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% else %}
                    <tr class="text-center" style="font-weight: bold; color:gray;">
                        <td class="all_view" colspan="4">
                            <i class="fas fa-info-circle"></i>&nbsp;작성한 댓글이 없습니다.
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade show" id="anonymous_comment" role="tabpanel" aria-labelledby="anonymous-comment-tab">
            <table class="table table-sm table-hover">
                <thead style="border-top: 1px solid #dee2e6;">
                    <tr class="text-center">
                        <th class="all_view_title"></th>
                        <th class="text-left all_view_title">게시글</th>
                        <th class="text-left all_view_title">댓글내용</th>
                        <th class="all_view_title">작성일</th>
                    </tr>
                </thead>
                <tbody>
                    {% if anonymous_comment_list %}
                        {% for comment in anonymous_comment_list %}
                            <tr class="text-center" style="font-weight: bold; cursor:pointer;" onclick="location.href='/anonymous/{{ comment.post.id }}/'">
                                <td class="all_view">{{ comment.post.id }}</td>
                                <td class="text-left all_view">{{ comment.post|truncatechars:8 }}</td>
                                <td class="text-left all_view" style="width:50%">
                                {{ comment.content|truncatechars:30 }}
                                </td>
                                {% if comment.created_string == False %}
                                <td class="all_view">{{ comment.created|date:'m월 d일' }}</td>
                                {% else %}
                                <td class="all_view">{{ comment.created_string }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    {% else %}
                    <tr class="text-center" style="font-weight: bold; color:gray;">
                        <td class="all_view" colspan="4">
                            <i class="fas fa-info-circle"></i>&nbsp;작성한 댓글이 없습니다.
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/users/register_email.html
{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 이메일 인증 발송</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">FOCUS홈페이지 회원가입을 축하드립니다.<br>아래 링크를 클릭하여 로그인 해주시기 바랍니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'users:activate' uid64=uid token=token %}">인증하기</a></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}